// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sixelping-command.proto

package sixelping_command

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewDeltaImageRequest struct {
	Image                []byte   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewDeltaImageRequest) Reset()         { *m = NewDeltaImageRequest{} }
func (m *NewDeltaImageRequest) String() string { return proto.CompactTextString(m) }
func (*NewDeltaImageRequest) ProtoMessage()    {}
func (*NewDeltaImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc675ceef4b1ed56, []int{0}
}

func (m *NewDeltaImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewDeltaImageRequest.Unmarshal(m, b)
}
func (m *NewDeltaImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewDeltaImageRequest.Marshal(b, m, deterministic)
}
func (m *NewDeltaImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewDeltaImageRequest.Merge(m, src)
}
func (m *NewDeltaImageRequest) XXX_Size() int {
	return xxx_messageInfo_NewDeltaImageRequest.Size(m)
}
func (m *NewDeltaImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewDeltaImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewDeltaImageRequest proto.InternalMessageInfo

func (m *NewDeltaImageRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type RenderedImageResponse struct {
	Image                []byte   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderedImageResponse) Reset()         { *m = RenderedImageResponse{} }
func (m *RenderedImageResponse) String() string { return proto.CompactTextString(m) }
func (*RenderedImageResponse) ProtoMessage()    {}
func (*RenderedImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc675ceef4b1ed56, []int{1}
}

func (m *RenderedImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderedImageResponse.Unmarshal(m, b)
}
func (m *RenderedImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderedImageResponse.Marshal(b, m, deterministic)
}
func (m *RenderedImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderedImageResponse.Merge(m, src)
}
func (m *RenderedImageResponse) XXX_Size() int {
	return xxx_messageInfo_RenderedImageResponse.Size(m)
}
func (m *RenderedImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderedImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenderedImageResponse proto.InternalMessageInfo

func (m *RenderedImageResponse) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type CanvasParametersResponse struct {
	Width                uint32   `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Fps                  uint32   `protobuf:"varint,3,opt,name=fps,proto3" json:"fps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanvasParametersResponse) Reset()         { *m = CanvasParametersResponse{} }
func (m *CanvasParametersResponse) String() string { return proto.CompactTextString(m) }
func (*CanvasParametersResponse) ProtoMessage()    {}
func (*CanvasParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc675ceef4b1ed56, []int{2}
}

func (m *CanvasParametersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanvasParametersResponse.Unmarshal(m, b)
}
func (m *CanvasParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanvasParametersResponse.Marshal(b, m, deterministic)
}
func (m *CanvasParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanvasParametersResponse.Merge(m, src)
}
func (m *CanvasParametersResponse) XXX_Size() int {
	return xxx_messageInfo_CanvasParametersResponse.Size(m)
}
func (m *CanvasParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CanvasParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CanvasParametersResponse proto.InternalMessageInfo

func (m *CanvasParametersResponse) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *CanvasParametersResponse) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *CanvasParametersResponse) GetFps() uint32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

//Message to send metrics out
type MetricsDatapoint struct {
	Ipackets             uint64   `protobuf:"varint,1,opt,name=ipackets,proto3" json:"ipackets,omitempty"`
	Opackets             uint64   `protobuf:"varint,2,opt,name=opackets,proto3" json:"opackets,omitempty"`
	Dpackets             uint64   `protobuf:"varint,3,opt,name=dpackets,proto3" json:"dpackets,omitempty"`
	Ibytes               uint64   `protobuf:"varint,4,opt,name=ibytes,proto3" json:"ibytes,omitempty"`
	Obytes               uint64   `protobuf:"varint,5,opt,name=obytes,proto3" json:"obytes,omitempty"`
	Mac                  string   `protobuf:"bytes,6,opt,name=mac,proto3" json:"mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsDatapoint) Reset()         { *m = MetricsDatapoint{} }
func (m *MetricsDatapoint) String() string { return proto.CompactTextString(m) }
func (*MetricsDatapoint) ProtoMessage()    {}
func (*MetricsDatapoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc675ceef4b1ed56, []int{3}
}

func (m *MetricsDatapoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsDatapoint.Unmarshal(m, b)
}
func (m *MetricsDatapoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsDatapoint.Marshal(b, m, deterministic)
}
func (m *MetricsDatapoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsDatapoint.Merge(m, src)
}
func (m *MetricsDatapoint) XXX_Size() int {
	return xxx_messageInfo_MetricsDatapoint.Size(m)
}
func (m *MetricsDatapoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsDatapoint.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsDatapoint proto.InternalMessageInfo

func (m *MetricsDatapoint) GetIpackets() uint64 {
	if m != nil {
		return m.Ipackets
	}
	return 0
}

func (m *MetricsDatapoint) GetOpackets() uint64 {
	if m != nil {
		return m.Opackets
	}
	return 0
}

func (m *MetricsDatapoint) GetDpackets() uint64 {
	if m != nil {
		return m.Dpackets
	}
	return 0
}

func (m *MetricsDatapoint) GetIbytes() uint64 {
	if m != nil {
		return m.Ibytes
	}
	return 0
}

func (m *MetricsDatapoint) GetObytes() uint64 {
	if m != nil {
		return m.Obytes
	}
	return 0
}

func (m *MetricsDatapoint) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func init() {
	proto.RegisterType((*NewDeltaImageRequest)(nil), "NewDeltaImageRequest")
	proto.RegisterType((*RenderedImageResponse)(nil), "RenderedImageResponse")
	proto.RegisterType((*CanvasParametersResponse)(nil), "CanvasParametersResponse")
	proto.RegisterType((*MetricsDatapoint)(nil), "MetricsDatapoint")
}

func init() { proto.RegisterFile("sixelping-command.proto", fileDescriptor_bc675ceef4b1ed56) }

var fileDescriptor_bc675ceef4b1ed56 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x5f, 0x6b, 0xe2, 0x40,
	0x14, 0xc5, 0x8d, 0xff, 0xd8, 0x1d, 0x56, 0xd0, 0x59, 0x75, 0xb3, 0xd9, 0x17, 0xc9, 0x93, 0x0f,
	0xeb, 0x08, 0xbb, 0xaf, 0x7d, 0x28, 0xd4, 0x22, 0x2d, 0xb4, 0x94, 0x94, 0xbe, 0xf4, 0x6d, 0x4c,
	0xae, 0x71, 0xa8, 0xc9, 0x4c, 0x33, 0xd7, 0x5a, 0x3f, 0x50, 0xa1, 0x1f, 0xb3, 0x4c, 0x26, 0x29,
	0x2a, 0xa6, 0x6f, 0xf9, 0x9d, 0x73, 0x6f, 0xb8, 0x9c, 0x33, 0xe4, 0x97, 0x16, 0xaf, 0xb0, 0x56,
	0x22, 0x8d, 0x27, 0xa1, 0x4c, 0x12, 0x9e, 0x46, 0x4c, 0x65, 0x12, 0xa5, 0xf7, 0x27, 0x96, 0x32,
	0x5e, 0xc3, 0x34, 0xa7, 0xc5, 0x66, 0x39, 0x85, 0x44, 0xe1, 0xce, 0x9a, 0xfe, 0x5f, 0xd2, 0xbf,
	0x85, 0xed, 0x0c, 0xd6, 0xc8, 0xaf, 0x12, 0x1e, 0x43, 0x00, 0xcf, 0x1b, 0xd0, 0x48, 0xfb, 0xa4,
	0x25, 0x0c, 0xbb, 0xce, 0xc8, 0x19, 0xff, 0x08, 0x2c, 0xf8, 0x13, 0x32, 0x08, 0x20, 0x8d, 0x20,
	0x83, 0xa8, 0x98, 0xd6, 0x4a, 0xa6, 0x1a, 0x2a, 0xc6, 0x1f, 0x89, 0x7b, 0xc1, 0xd3, 0x17, 0xae,
	0xef, 0x78, 0xc6, 0x13, 0x40, 0xc8, 0xf4, 0xfe, 0xc6, 0x56, 0x44, 0xb8, 0xca, 0x37, 0x3a, 0x81,
	0x05, 0x3a, 0x24, 0xed, 0x15, 0x88, 0x78, 0x85, 0x6e, 0x3d, 0x97, 0x0b, 0xa2, 0x5d, 0xd2, 0x58,
	0x2a, 0xed, 0x36, 0x72, 0xd1, 0x7c, 0xfa, 0xef, 0x0e, 0xe9, 0xde, 0x00, 0x66, 0x22, 0xd4, 0x33,
	0x8e, 0x5c, 0x49, 0x91, 0x22, 0xf5, 0xc8, 0x37, 0xa1, 0x78, 0xf8, 0x04, 0xa8, 0xf3, 0xff, 0x36,
	0x83, 0x4f, 0x36, 0x9e, 0x2c, 0xbd, 0xba, 0xf5, 0xe4, 0x9e, 0x17, 0x95, 0x5e, 0xc3, 0x7a, 0x25,
	0x9b, 0x93, 0xc4, 0x62, 0x87, 0xa0, 0xdd, 0x66, 0xee, 0x14, 0x64, 0x74, 0x69, 0xf5, 0x96, 0xd5,
	0x2d, 0x99, 0x53, 0x13, 0x1e, 0xba, 0xed, 0x91, 0x33, 0xfe, 0x1e, 0x98, 0xcf, 0x7f, 0x6f, 0x75,
	0xd2, 0xbb, 0x2f, 0xcb, 0x29, 0xf2, 0xcb, 0xe8, 0x39, 0xe9, 0x1c, 0x24, 0x4f, 0x07, 0xec, 0x54,
	0x13, 0xde, 0x90, 0xd9, 0xfe, 0x58, 0xd9, 0x1f, 0xbb, 0x34, 0xfd, 0xf9, 0x35, 0x7a, 0x4d, 0x7e,
	0xce, 0x01, 0x8f, 0x13, 0xa6, 0x15, 0x0b, 0xde, 0x6f, 0x56, 0x55, 0x86, 0x5f, 0xa3, 0x67, 0xa4,
	0x53, 0xa4, 0xf9, 0xa0, 0x22, 0x8e, 0x40, 0x7b, 0xec, 0x38, 0xdd, 0x2f, 0x2e, 0x99, 0x91, 0xee,
	0x1c, 0xf0, 0xe0, 0x69, 0x54, 0x9e, 0x31, 0x64, 0x27, 0x9f, 0x90, 0x5f, 0x5b, 0xb4, 0xf3, 0xc9,
	0xff, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x10, 0x9e, 0x52, 0xca, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SixelpingRendererClient is the client API for SixelpingRenderer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SixelpingRendererClient interface {
	NewDeltaImage(ctx context.Context, in *NewDeltaImageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetCanvasParameters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CanvasParametersResponse, error)
	MetricsUpdate(ctx context.Context, in *MetricsDatapoint, opts ...grpc.CallOption) (*empty.Empty, error)
	GetRenderedImage(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RenderedImageResponse, error)
}

type sixelpingRendererClient struct {
	cc *grpc.ClientConn
}

func NewSixelpingRendererClient(cc *grpc.ClientConn) SixelpingRendererClient {
	return &sixelpingRendererClient{cc}
}

func (c *sixelpingRendererClient) NewDeltaImage(ctx context.Context, in *NewDeltaImageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/SixelpingRenderer/NewDeltaImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sixelpingRendererClient) GetCanvasParameters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CanvasParametersResponse, error) {
	out := new(CanvasParametersResponse)
	err := c.cc.Invoke(ctx, "/SixelpingRenderer/GetCanvasParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sixelpingRendererClient) MetricsUpdate(ctx context.Context, in *MetricsDatapoint, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/SixelpingRenderer/MetricsUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sixelpingRendererClient) GetRenderedImage(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RenderedImageResponse, error) {
	out := new(RenderedImageResponse)
	err := c.cc.Invoke(ctx, "/SixelpingRenderer/GetRenderedImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SixelpingRendererServer is the server API for SixelpingRenderer service.
type SixelpingRendererServer interface {
	NewDeltaImage(context.Context, *NewDeltaImageRequest) (*empty.Empty, error)
	GetCanvasParameters(context.Context, *empty.Empty) (*CanvasParametersResponse, error)
	MetricsUpdate(context.Context, *MetricsDatapoint) (*empty.Empty, error)
	GetRenderedImage(context.Context, *empty.Empty) (*RenderedImageResponse, error)
}

// UnimplementedSixelpingRendererServer can be embedded to have forward compatible implementations.
type UnimplementedSixelpingRendererServer struct {
}

func (*UnimplementedSixelpingRendererServer) NewDeltaImage(ctx context.Context, req *NewDeltaImageRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewDeltaImage not implemented")
}
func (*UnimplementedSixelpingRendererServer) GetCanvasParameters(ctx context.Context, req *empty.Empty) (*CanvasParametersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCanvasParameters not implemented")
}
func (*UnimplementedSixelpingRendererServer) MetricsUpdate(ctx context.Context, req *MetricsDatapoint) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetricsUpdate not implemented")
}
func (*UnimplementedSixelpingRendererServer) GetRenderedImage(ctx context.Context, req *empty.Empty) (*RenderedImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRenderedImage not implemented")
}

func RegisterSixelpingRendererServer(s *grpc.Server, srv SixelpingRendererServer) {
	s.RegisterService(&_SixelpingRenderer_serviceDesc, srv)
}

func _SixelpingRenderer_NewDeltaImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewDeltaImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SixelpingRendererServer).NewDeltaImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SixelpingRenderer/NewDeltaImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SixelpingRendererServer).NewDeltaImage(ctx, req.(*NewDeltaImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SixelpingRenderer_GetCanvasParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SixelpingRendererServer).GetCanvasParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SixelpingRenderer/GetCanvasParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SixelpingRendererServer).GetCanvasParameters(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SixelpingRenderer_MetricsUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsDatapoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SixelpingRendererServer).MetricsUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SixelpingRenderer/MetricsUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SixelpingRendererServer).MetricsUpdate(ctx, req.(*MetricsDatapoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _SixelpingRenderer_GetRenderedImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SixelpingRendererServer).GetRenderedImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SixelpingRenderer/GetRenderedImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SixelpingRendererServer).GetRenderedImage(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SixelpingRenderer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SixelpingRenderer",
	HandlerType: (*SixelpingRendererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewDeltaImage",
			Handler:    _SixelpingRenderer_NewDeltaImage_Handler,
		},
		{
			MethodName: "GetCanvasParameters",
			Handler:    _SixelpingRenderer_GetCanvasParameters_Handler,
		},
		{
			MethodName: "MetricsUpdate",
			Handler:    _SixelpingRenderer_MetricsUpdate_Handler,
		},
		{
			MethodName: "GetRenderedImage",
			Handler:    _SixelpingRenderer_GetRenderedImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sixelping-command.proto",
}
