// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sixelping-command.proto

package sixelping_command

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewDeltaImageRequest struct {
	Image                []byte   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewDeltaImageRequest) Reset()         { *m = NewDeltaImageRequest{} }
func (m *NewDeltaImageRequest) String() string { return proto.CompactTextString(m) }
func (*NewDeltaImageRequest) ProtoMessage()    {}
func (*NewDeltaImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc675ceef4b1ed56, []int{0}
}

func (m *NewDeltaImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewDeltaImageRequest.Unmarshal(m, b)
}
func (m *NewDeltaImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewDeltaImageRequest.Marshal(b, m, deterministic)
}
func (m *NewDeltaImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewDeltaImageRequest.Merge(m, src)
}
func (m *NewDeltaImageRequest) XXX_Size() int {
	return xxx_messageInfo_NewDeltaImageRequest.Size(m)
}
func (m *NewDeltaImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewDeltaImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewDeltaImageRequest proto.InternalMessageInfo

func (m *NewDeltaImageRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type RenderedImageResponse struct {
	Image                []byte   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderedImageResponse) Reset()         { *m = RenderedImageResponse{} }
func (m *RenderedImageResponse) String() string { return proto.CompactTextString(m) }
func (*RenderedImageResponse) ProtoMessage()    {}
func (*RenderedImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc675ceef4b1ed56, []int{1}
}

func (m *RenderedImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderedImageResponse.Unmarshal(m, b)
}
func (m *RenderedImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderedImageResponse.Marshal(b, m, deterministic)
}
func (m *RenderedImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderedImageResponse.Merge(m, src)
}
func (m *RenderedImageResponse) XXX_Size() int {
	return xxx_messageInfo_RenderedImageResponse.Size(m)
}
func (m *RenderedImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderedImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenderedImageResponse proto.InternalMessageInfo

func (m *RenderedImageResponse) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type CanvasParametersResponse struct {
	Width                uint32   `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Fps                  uint32   `protobuf:"varint,3,opt,name=fps,proto3" json:"fps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanvasParametersResponse) Reset()         { *m = CanvasParametersResponse{} }
func (m *CanvasParametersResponse) String() string { return proto.CompactTextString(m) }
func (*CanvasParametersResponse) ProtoMessage()    {}
func (*CanvasParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc675ceef4b1ed56, []int{2}
}

func (m *CanvasParametersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanvasParametersResponse.Unmarshal(m, b)
}
func (m *CanvasParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanvasParametersResponse.Marshal(b, m, deterministic)
}
func (m *CanvasParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanvasParametersResponse.Merge(m, src)
}
func (m *CanvasParametersResponse) XXX_Size() int {
	return xxx_messageInfo_CanvasParametersResponse.Size(m)
}
func (m *CanvasParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CanvasParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CanvasParametersResponse proto.InternalMessageInfo

func (m *CanvasParametersResponse) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *CanvasParametersResponse) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *CanvasParametersResponse) GetFps() uint32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

//Message to send metrics out
type MetricsDatapoint struct {
	Entry                []*MetricsDatapoint_Entry `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MetricsDatapoint) Reset()         { *m = MetricsDatapoint{} }
func (m *MetricsDatapoint) String() string { return proto.CompactTextString(m) }
func (*MetricsDatapoint) ProtoMessage()    {}
func (*MetricsDatapoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc675ceef4b1ed56, []int{3}
}

func (m *MetricsDatapoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsDatapoint.Unmarshal(m, b)
}
func (m *MetricsDatapoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsDatapoint.Marshal(b, m, deterministic)
}
func (m *MetricsDatapoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsDatapoint.Merge(m, src)
}
func (m *MetricsDatapoint) XXX_Size() int {
	return xxx_messageInfo_MetricsDatapoint.Size(m)
}
func (m *MetricsDatapoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsDatapoint.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsDatapoint proto.InternalMessageInfo

func (m *MetricsDatapoint) GetEntry() []*MetricsDatapoint_Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type MetricsDatapoint_Entry struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Oo:
	//	*MetricsDatapoint_Entry_ValueU64
	//	*MetricsDatapoint_Entry_ValueDbl
	//	*MetricsDatapoint_Entry_ValueStr
	Oo                   isMetricsDatapoint_Entry_Oo     `protobuf_oneof:"oo"`
	Label                []*MetricsDatapoint_Entry_Label `protobuf:"bytes,5,rep,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *MetricsDatapoint_Entry) Reset()         { *m = MetricsDatapoint_Entry{} }
func (m *MetricsDatapoint_Entry) String() string { return proto.CompactTextString(m) }
func (*MetricsDatapoint_Entry) ProtoMessage()    {}
func (*MetricsDatapoint_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc675ceef4b1ed56, []int{3, 0}
}

func (m *MetricsDatapoint_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsDatapoint_Entry.Unmarshal(m, b)
}
func (m *MetricsDatapoint_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsDatapoint_Entry.Marshal(b, m, deterministic)
}
func (m *MetricsDatapoint_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsDatapoint_Entry.Merge(m, src)
}
func (m *MetricsDatapoint_Entry) XXX_Size() int {
	return xxx_messageInfo_MetricsDatapoint_Entry.Size(m)
}
func (m *MetricsDatapoint_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsDatapoint_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsDatapoint_Entry proto.InternalMessageInfo

func (m *MetricsDatapoint_Entry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isMetricsDatapoint_Entry_Oo interface {
	isMetricsDatapoint_Entry_Oo()
}

type MetricsDatapoint_Entry_ValueU64 struct {
	ValueU64 uint64 `protobuf:"varint,2,opt,name=value_u64,json=valueU64,proto3,oneof"`
}

type MetricsDatapoint_Entry_ValueDbl struct {
	ValueDbl float64 `protobuf:"fixed64,3,opt,name=value_dbl,json=valueDbl,proto3,oneof"`
}

type MetricsDatapoint_Entry_ValueStr struct {
	ValueStr string `protobuf:"bytes,4,opt,name=value_str,json=valueStr,proto3,oneof"`
}

func (*MetricsDatapoint_Entry_ValueU64) isMetricsDatapoint_Entry_Oo() {}

func (*MetricsDatapoint_Entry_ValueDbl) isMetricsDatapoint_Entry_Oo() {}

func (*MetricsDatapoint_Entry_ValueStr) isMetricsDatapoint_Entry_Oo() {}

func (m *MetricsDatapoint_Entry) GetOo() isMetricsDatapoint_Entry_Oo {
	if m != nil {
		return m.Oo
	}
	return nil
}

func (m *MetricsDatapoint_Entry) GetValueU64() uint64 {
	if x, ok := m.GetOo().(*MetricsDatapoint_Entry_ValueU64); ok {
		return x.ValueU64
	}
	return 0
}

func (m *MetricsDatapoint_Entry) GetValueDbl() float64 {
	if x, ok := m.GetOo().(*MetricsDatapoint_Entry_ValueDbl); ok {
		return x.ValueDbl
	}
	return 0
}

func (m *MetricsDatapoint_Entry) GetValueStr() string {
	if x, ok := m.GetOo().(*MetricsDatapoint_Entry_ValueStr); ok {
		return x.ValueStr
	}
	return ""
}

func (m *MetricsDatapoint_Entry) GetLabel() []*MetricsDatapoint_Entry_Label {
	if m != nil {
		return m.Label
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MetricsDatapoint_Entry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MetricsDatapoint_Entry_ValueU64)(nil),
		(*MetricsDatapoint_Entry_ValueDbl)(nil),
		(*MetricsDatapoint_Entry_ValueStr)(nil),
	}
}

type MetricsDatapoint_Entry_Label struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsDatapoint_Entry_Label) Reset()         { *m = MetricsDatapoint_Entry_Label{} }
func (m *MetricsDatapoint_Entry_Label) String() string { return proto.CompactTextString(m) }
func (*MetricsDatapoint_Entry_Label) ProtoMessage()    {}
func (*MetricsDatapoint_Entry_Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc675ceef4b1ed56, []int{3, 0, 0}
}

func (m *MetricsDatapoint_Entry_Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsDatapoint_Entry_Label.Unmarshal(m, b)
}
func (m *MetricsDatapoint_Entry_Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsDatapoint_Entry_Label.Marshal(b, m, deterministic)
}
func (m *MetricsDatapoint_Entry_Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsDatapoint_Entry_Label.Merge(m, src)
}
func (m *MetricsDatapoint_Entry_Label) XXX_Size() int {
	return xxx_messageInfo_MetricsDatapoint_Entry_Label.Size(m)
}
func (m *MetricsDatapoint_Entry_Label) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsDatapoint_Entry_Label.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsDatapoint_Entry_Label proto.InternalMessageInfo

func (m *MetricsDatapoint_Entry_Label) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetricsDatapoint_Entry_Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*NewDeltaImageRequest)(nil), "NewDeltaImageRequest")
	proto.RegisterType((*RenderedImageResponse)(nil), "RenderedImageResponse")
	proto.RegisterType((*CanvasParametersResponse)(nil), "CanvasParametersResponse")
	proto.RegisterType((*MetricsDatapoint)(nil), "MetricsDatapoint")
	proto.RegisterType((*MetricsDatapoint_Entry)(nil), "MetricsDatapoint.Entry")
	proto.RegisterType((*MetricsDatapoint_Entry_Label)(nil), "MetricsDatapoint.Entry.Label")
}

func init() { proto.RegisterFile("sixelping-command.proto", fileDescriptor_bc675ceef4b1ed56) }

var fileDescriptor_bc675ceef4b1ed56 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x9b, 0xb6, 0x99, 0xe8, 0x83, 0x4a, 0x9d, 0xe9, 0xba, 0x10, 0x34, 0x69, 0xca, 0x69,
	0x07, 0xea, 0x89, 0x6d, 0xda, 0x89, 0x03, 0x82, 0x4e, 0x03, 0x04, 0x08, 0x79, 0xda, 0x85, 0x0b,
	0x72, 0x96, 0xb7, 0x34, 0x52, 0x62, 0x07, 0xfb, 0x75, 0x63, 0x7f, 0x10, 0x17, 0xfe, 0x30, 0xfe,
	0x0e, 0x14, 0xbb, 0xdb, 0x58, 0x69, 0xb8, 0xf9, 0x7b, 0xdf, 0x67, 0xeb, 0x27, 0xbf, 0x0f, 0xb6,
	0x6d, 0xf1, 0x03, 0xcb, 0xba, 0x50, 0xf9, 0xf4, 0x42, 0x57, 0x95, 0x54, 0x19, 0xaf, 0x8d, 0x26,
	0x1d, 0x3f, 0xcf, 0xb5, 0xce, 0x4b, 0xdc, 0x77, 0x2a, 0x5d, 0x5c, 0xee, 0x63, 0x55, 0xd3, 0x8d,
	0x37, 0x93, 0x17, 0x30, 0xfe, 0x8c, 0xd7, 0x33, 0x2c, 0x49, 0xbe, 0xaf, 0x64, 0x8e, 0x02, 0xbf,
	0x2f, 0xd0, 0x12, 0x1b, 0x43, 0x58, 0x34, 0x3a, 0x0a, 0x76, 0x83, 0xbd, 0x27, 0xc2, 0x8b, 0x64,
	0x0a, 0x5b, 0x02, 0x55, 0x86, 0x06, 0xb3, 0x65, 0xda, 0xd6, 0x5a, 0x59, 0x6c, 0x89, 0x7f, 0x85,
	0xe8, 0xad, 0x54, 0x57, 0xd2, 0x7e, 0x91, 0x46, 0x56, 0x48, 0x68, 0xec, 0xdf, 0x37, 0xae, 0x8b,
	0x8c, 0xe6, 0xee, 0xc6, 0x50, 0x78, 0xc1, 0x26, 0xb0, 0x31, 0xc7, 0x22, 0x9f, 0x53, 0xd4, 0x75,
	0xe3, 0xa5, 0x62, 0x23, 0xe8, 0x5d, 0xd6, 0x36, 0xea, 0xb9, 0x61, 0x73, 0x4c, 0x7e, 0x75, 0x61,
	0xf4, 0x09, 0xc9, 0x14, 0x17, 0x76, 0x26, 0x49, 0xd6, 0xba, 0x50, 0xc4, 0xa6, 0x10, 0xa2, 0x22,
	0x73, 0x13, 0x05, 0xbb, 0xbd, 0xbd, 0xc7, 0x07, 0xdb, 0x7c, 0x35, 0xc1, 0x4f, 0x1a, 0x5b, 0xf8,
	0x54, 0xfc, 0x3b, 0x80, 0xd0, 0x0d, 0x18, 0x83, 0xbe, 0x92, 0x95, 0xc7, 0x1f, 0x08, 0x77, 0x66,
	0x3b, 0x30, 0xb8, 0x92, 0xe5, 0x02, 0xbf, 0x2d, 0x8e, 0x8f, 0x1c, 0x4e, 0xff, 0x5d, 0x47, 0x3c,
	0x72, 0xa3, 0xf3, 0xe3, 0xa3, 0x7b, 0x3b, 0x4b, 0x4b, 0x07, 0x16, 0xdc, 0xd9, 0xb3, 0xb4, 0xbc,
	0xb7, 0x2d, 0x99, 0xa8, 0xdf, 0x3c, 0x7b, 0x67, 0x9f, 0x91, 0x61, 0x87, 0x10, 0x96, 0x32, 0xc5,
	0x32, 0x0a, 0x1d, 0xe9, 0x4e, 0x0b, 0x29, 0xff, 0xd8, 0x84, 0x84, 0xcf, 0xc6, 0x2f, 0x21, 0x74,
	0x7a, 0x2d, 0xee, 0x18, 0x42, 0xf7, 0xba, 0x43, 0x1d, 0x08, 0x2f, 0xde, 0xf4, 0xa1, 0xab, 0xf5,
	0xc1, 0xcf, 0x2e, 0x6c, 0x9e, 0xdd, 0xd6, 0x63, 0xb9, 0x41, 0xc3, 0x5e, 0xc3, 0xf0, 0xc1, 0xee,
	0xd9, 0x16, 0x5f, 0xd7, 0x85, 0x78, 0xc2, 0x7d, 0x83, 0xf8, 0x6d, 0x83, 0xf8, 0x49, 0xd3, 0xa0,
	0xa4, 0xc3, 0x3e, 0xc0, 0xd3, 0x53, 0xa4, 0xd5, 0x1d, 0xb3, 0x96, 0x0b, 0xf1, 0x33, 0xde, 0x56,
	0x87, 0xa4, 0xc3, 0x5e, 0xc1, 0x70, 0xf9, 0x07, 0xe7, 0x75, 0x26, 0x09, 0xd9, 0xe6, 0x3f, 0x7f,
	0xf2, 0x1f, 0x92, 0x19, 0x8c, 0x4e, 0x91, 0x1e, 0x94, 0xb3, 0x15, 0x63, 0xc2, 0xd7, 0x96, 0x38,
	0xe9, 0xa4, 0x1b, 0x2e, 0x79, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x06, 0x5e, 0x1e, 0x4c,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SixelpingRendererClient is the client API for SixelpingRenderer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SixelpingRendererClient interface {
	NewDeltaImage(ctx context.Context, in *NewDeltaImageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetCanvasParameters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CanvasParametersResponse, error)
	MetricsUpdate(ctx context.Context, in *MetricsDatapoint, opts ...grpc.CallOption) (*empty.Empty, error)
	GetRenderedImage(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RenderedImageResponse, error)
}

type sixelpingRendererClient struct {
	cc *grpc.ClientConn
}

func NewSixelpingRendererClient(cc *grpc.ClientConn) SixelpingRendererClient {
	return &sixelpingRendererClient{cc}
}

func (c *sixelpingRendererClient) NewDeltaImage(ctx context.Context, in *NewDeltaImageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/SixelpingRenderer/NewDeltaImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sixelpingRendererClient) GetCanvasParameters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CanvasParametersResponse, error) {
	out := new(CanvasParametersResponse)
	err := c.cc.Invoke(ctx, "/SixelpingRenderer/GetCanvasParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sixelpingRendererClient) MetricsUpdate(ctx context.Context, in *MetricsDatapoint, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/SixelpingRenderer/MetricsUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sixelpingRendererClient) GetRenderedImage(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RenderedImageResponse, error) {
	out := new(RenderedImageResponse)
	err := c.cc.Invoke(ctx, "/SixelpingRenderer/GetRenderedImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SixelpingRendererServer is the server API for SixelpingRenderer service.
type SixelpingRendererServer interface {
	NewDeltaImage(context.Context, *NewDeltaImageRequest) (*empty.Empty, error)
	GetCanvasParameters(context.Context, *empty.Empty) (*CanvasParametersResponse, error)
	MetricsUpdate(context.Context, *MetricsDatapoint) (*empty.Empty, error)
	GetRenderedImage(context.Context, *empty.Empty) (*RenderedImageResponse, error)
}

// UnimplementedSixelpingRendererServer can be embedded to have forward compatible implementations.
type UnimplementedSixelpingRendererServer struct {
}

func (*UnimplementedSixelpingRendererServer) NewDeltaImage(ctx context.Context, req *NewDeltaImageRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewDeltaImage not implemented")
}
func (*UnimplementedSixelpingRendererServer) GetCanvasParameters(ctx context.Context, req *empty.Empty) (*CanvasParametersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCanvasParameters not implemented")
}
func (*UnimplementedSixelpingRendererServer) MetricsUpdate(ctx context.Context, req *MetricsDatapoint) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetricsUpdate not implemented")
}
func (*UnimplementedSixelpingRendererServer) GetRenderedImage(ctx context.Context, req *empty.Empty) (*RenderedImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRenderedImage not implemented")
}

func RegisterSixelpingRendererServer(s *grpc.Server, srv SixelpingRendererServer) {
	s.RegisterService(&_SixelpingRenderer_serviceDesc, srv)
}

func _SixelpingRenderer_NewDeltaImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewDeltaImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SixelpingRendererServer).NewDeltaImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SixelpingRenderer/NewDeltaImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SixelpingRendererServer).NewDeltaImage(ctx, req.(*NewDeltaImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SixelpingRenderer_GetCanvasParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SixelpingRendererServer).GetCanvasParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SixelpingRenderer/GetCanvasParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SixelpingRendererServer).GetCanvasParameters(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SixelpingRenderer_MetricsUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsDatapoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SixelpingRendererServer).MetricsUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SixelpingRenderer/MetricsUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SixelpingRendererServer).MetricsUpdate(ctx, req.(*MetricsDatapoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _SixelpingRenderer_GetRenderedImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SixelpingRendererServer).GetRenderedImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SixelpingRenderer/GetRenderedImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SixelpingRendererServer).GetRenderedImage(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SixelpingRenderer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SixelpingRenderer",
	HandlerType: (*SixelpingRendererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewDeltaImage",
			Handler:    _SixelpingRenderer_NewDeltaImage_Handler,
		},
		{
			MethodName: "GetCanvasParameters",
			Handler:    _SixelpingRenderer_GetCanvasParameters_Handler,
		},
		{
			MethodName: "MetricsUpdate",
			Handler:    _SixelpingRenderer_MetricsUpdate_Handler,
		},
		{
			MethodName: "GetRenderedImage",
			Handler:    _SixelpingRenderer_GetRenderedImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sixelping-command.proto",
}
